### PR TITLE
Adds UpdateCollection use case

### LINKED ISSUE #200: Edit Collection use case [JS-Dataverse]
## Overview of the feature request

Allowing for users of the package to edit a collection (dataverse) within a Dataverse instance specified by the users.

## What inspired the request?

Q4 Roadmap

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to js-dataverse?

Collection (dataverse) edition

## Any open or closed issues related to this feature request?

None

### PR DESCRIPTION
**Pull request by GPortas**
## What this PR does / why we need it:

Implements UpdateCollection use case.

## Which issue(s) this PR closes:

- Closes #200 

## Related Dataverse PRs:

- Depends on https://github.com/IQSS/dataverse/pull/10925

**Environment variables should be changed before moving this PR to Ready For QA**

## Special notes for your reviewer:

None

## Suggestions on how to test this:

Visual inspection of the code and tests on GitHub actions.

## Is there a release notes update needed for this change?:

N/A

## Additional documentation:

No

### CODE REVIEW

**Comment by GPortas** [comment]
Waiting for https://github.com/IQSS/dataverse/pull/10925 to be ready

**Review by g-saracca — APPROVED** [review]

**Comment by g-saracca** [comment]
@ofahimIQSS we should maybe wait to test this until the related [dataverse repo PR](https://github.com/IQSS/dataverse/pull/10925) is done.
Once that PR is merged, we should change .env variables back to using unstable docker image.

**Comment by ofahimIQSS** [comment]
It looks like the job @github-actions
deploy_pr / publish-gpr (pull_request) is failing - https://github.com/IQSS/dataverse-client-javascript/actions/runs/11477537944/job/32481330196?pr=204

**Comment by ofahimIQSS** [comment]
Reviewed - Merging PR

**Pull request merged**
