### PR TITLE
Add filters to getDatasetFiles use case

### PR DESCRIPTION
**Pull request by GPortas**
## What this PR does / why we need it:

Adds a new FileCriteria parameter to the getDatasetFiles use case, which applies different optional filters to the final API call.

Also includes a small refactor described in https://github.com/IQSS/dataverse-client-javascript/pull/80#discussion_r1298176950

Adds latestRestricted property to File model (dataFile level).

## Which issue(s) this PR closes:

- Closes #80

## Suggestions on how to test this:

- Visual inspection of the code
- Check unit and integration tests execution in GitHub actions

## Is there a release notes update needed for this change?:

Adds filters to getDatasetFiles use case

### CODE REVIEW

**Review by MellyGray — APPROVED** [review]
LGTM 🎉 nothing to add, let's move it forward!

**Comment by kcondon** [comment]
@GPortas Do you know where currently this is used in UI. In addition to automated tests, just wanted to try it out in pre SPA ui.

**Comment by MellyGray** [comment]
> @GPortas Do you know where currently this is used in UI. In addition to automated tests, just wanted to try it out in pre SPA ui.

Hi @kcondon ! You can try it out in this branch PR https://github.com/IQSS/dataverse-frontend/pull/173

**Comment by kcondon** [comment]
Sorry, first day back testing SPA and have temporarily forgotten some basic steps, like checking which repo the pr is for. :)

**Pull request merged**
