### PR TITLE
Extend get collection use case

### LINKED ISSUE #214: Extend GetCollection use case
We need to extend the GetCollection use case to return the next information also:

- contacts
- type
- usesMetadataFieldsFromParent
- usesBrowseSearchFacetsFromParent

This is needed for the Edit Collection page within the SPA.

### PR DESCRIPTION
**Pull request by g-saracca**
## What this PR does / why we need it:
Extends the GetCollection use case to return the next information also:
- contacts
- type
- isMetadataBlockRoot
- isFacetRoot

## Which issue(s) this PR closes:

- Closes #214 

## Suggestions on how to test this:
Visual code inspection and run tests (integration test was modified)

## Is there a release notes update needed for this change?:
No

## Additional documentation:
No

### CODE REVIEW

**Review by ChengShi-1 — APPROVED** [review]
It seems good, approve!

**Comment by ofahimIQSS** [comment]
@g-saracca it looks like publish-gpr failed when I tried to rerun the github actions: https://github.com/IQSS/dataverse-client-javascript/actions/runs/11836322422/job/33390578876?pr=215

**Comment by g-saracca** [comment]
Hi @ofahimIQSS, yep, we have [an open issue](https://github.com/IQSS/dataverse-client-javascript/issues/211) for fixing that behavior, its when you re-run de deploy_pr/publish-gpr action without any new commit.
The alpha deploy when merging to develop is working correctly.

**Comment by ofahimIQSS** [comment]
Merging PR

**Pull request merged**
