### PR TITLE
Adds new use case GetAllMetadataBlocks

### LINKED ISSUE #168: Create use case for getting all metadata blocks defined in the installation
## Overview of the feature request

We need this use case for the create collection page.

This use case will use the following endpoint from the API:
https://guides.dataverse.org/en/latest/api/native-api.html#show-info-about-all-metadata-blocks

We will reutilize logic and models from GetCollectionMetadataBlocks.

## What inspired the request?

- SPA needs

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to js-dataverse?

Use case for getting all metadata blocks defined in the installation

## Any open or closed issues related to this feature request?

None

### PR DESCRIPTION
**Pull request by GPortas**
## What this PR does / why we need it:

Adds new use case GetAllMetadataBlocks

## Which issue(s) this PR closes:

- Closes #168 

## Related Dataverse PRs:

None

## Special notes for your reviewer:

None

## Suggestions on how to test this:

Visual inspection and actions execution

### CODE REVIEW

**Review by g-saracca — APPROVED** [review]
All good 👍🏼 , approving 🚀

**Comment by ekraffmiller** [comment]
I am getting an error in the integration test, even though I see it is passing in the Github Action. Is this due to something lacking in my local environment?

Screenshot 2024-08-09 at 1 37 43 PM

**Comment by GPortas** [comment]
> I am getting an error in the integration test, even though I see it is passing in the Github Action. Is this due to something lacking in my local environment?
> 
> Screenshot 2024-08-09 at 1 37 43 PM

@ekraffmiller I have encountered that error in the past, and in my case it was related to DNS resolution in my Docker environment. Could you please try restarting Docker on your local machine and running the tests again?

**Comment by ekraffmiller** [comment]
> > I am getting an error in the integration test, even though I see it is passing in the Github Action. Is this due to something lacking in my local environment?
> > Screenshot 2024-08-09 at 1 37 43 PM
> 
> @ekraffmiller I have encountered that error in the past, and in my case it was related to DNS resolution in my Docker environment. Could you please try restarting Docker on your local machine and running the tests again?

That worked, thanks!

**Comment by ekraffmiller** [comment]
Looks good! merging

**Pull request merged**
