### PR TITLE
58 - Automatically reformat code

### LINKED ISSUE #58: automatically reformat code
As a test I just messed with some code and gave it some awful formatting:

```
import { ApiRepository } from '../../../core/infra/repositories/ApiRepository'; import { IAuthRepository } from '../../domain/repositories/IAuthRepository';

export class AuthRepository extends ApiRepository implements IAuthRepository {
 public async logout(): Promise<void> {
     return this.doPost('/logout', '')
         .then(() => undefined)
            .catch((error) => {
               throw error;
                    });
                      }
                           }
```

I was able to push it to a branch (which I plan to delete but for now you can see the commit at fbebab5).

I would love to have the feature from the frontend where code is formatted automatically. It was added somewhere around here: https://github.com/IQSS/dataverse-frontend/commit/f9af164688df59c390cd078a39436ce155017b3f

There's some discussion here as well: https://github.com/IQSS/dataverse-frontend/pull/4#discussion_r1108682935

That is to say, it would be great to reformat the code automatically before it is pushed to a branch. This will keep our code formatted the same way no matter how the code is edited.

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the automatic formatting to the repo using some pre-commit configurations. The pre-commits include:

1. Running the formatter
2. Running a typescript check to check the types
3. Fix all linter errors
4. Run the tests and check the coverage (95%)

A part from that:
- I added some changes to the ESlint and prettier config files to match the SPA formatting
- We were using a mix of jest, chai and sinon testing libraries, so I removed sinon and chai from the repo in favor of using only jest which simplifies the tests
- Since I added a coverage check to the pre-commits I had to add some tests to match the 95% coverage threshold
- I fixed some casting in some use cases because we were using the type casting `as number` instead of the real casting `parseInt()` and the tests were failing after changing from sinon assert to jest strict comparison.
- I rewrote some jest config files from javascript to typescript

## Which issue(s) this PR closes:

- Closes #58 

## Special notes for your reviewer:
There are a lot of changes, but these are just formatting changes so they shouldn't affect the features.

## Suggestions on how to test this:
1. Visual inspection of the code
5. Make a change to the source code in your local environment and commit the change to check that the pre-commit checks are running as expected
6. Uncommit the test commit

### CODE REVIEW

**Comment by GPortas** [comment]
@MellyGray Can you please resolve conflicts?

Please, do not prioritize this PR if you have other pending feature-related issues, which should be our focus for the community day.

**Comment by MellyGray** [comment]
@GPortas merge conflicts resolved

One question, should we merge this PR here to fix the markdown library?
- https://github.com/IQSS/dataverse-client-javascript/pull/130

**Comment by GPortas** [comment]
@MellyGray 

Yes, I just accepted and merged the PR. Can you please resolve the conflicts?

**Review by GPortas — COMMENTED** [review]
I just tested the commit command as described adding a few malformed lines and I don't see any command logs or any changes to the pushed changes.

logsgit

The pushed test changes are malformed:

malformedpushed

I will revert the pushed changes if necessary.

@MellyGray

**Comment by MellyGray** [comment]
@GPortas did you ran npm install to install the pre-commit package?

**Comment by GPortas** [comment]
@MellyGray I missed that step, thanks!

**Review by GPortas — APPROVED** [review]
LGTM

GitHub action registry push is failing since I had to force push to a previous commit to revert test commits.

**Pull request merged**
