### PR TITLE
117- Create use case to get the file citation

### LINKED ISSUE #117: Create use case to get the file citation
**Overview of the Feature Request**

The aim is to develop a new use case for retrieving a specific file citation 

This use case will be consumed from Dataverse SPA, although it should be applicable to other scenarios.

This use case depends on this issue to implement the API endpoint:
- https://github.com/IQSS/dataverse/issues/10240

**What kind of user is the feature intended for?**

- Use case consumer

**What inspired the request?**

- https://github.com/IQSS/dataverse-frontend/pull/269#issuecomment-1874193736
- https://github.com/IQSS/dataverse-frontend/issues/249

**What existing behavior do you want changed?**

None

**Any brand new behavior do you want to add to Dataverse?**

Get File citation use case

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse-frontend/issues/249

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds a new use case getFileCitation to get the file citation given the fileId and datasetVersion.

## Which issue(s) this PR closes:

- Closes #117 

## Related Dataverse PRs:

- Depends on https://github.com/IQSS/dataverse/issues/10240

## Suggestions on how to test this:
1. Visual inspection of the code
2. Check unit and integration tests execution in GitHub actions

## Is there a release notes update needed for this change?:
GetFileCitation use case added to the module

### CODE REVIEW

**Comment by MellyGray** [comment]
Waiting on https://github.com/IQSS/dataverse/issues/10240

**Review by ekraffmiller — COMMENTED** [review]
This looks good! I just have a question about what dataset version should be returned by default, it seems that JSF returns :latest-published, but we are returning :latest.  See Slack thread https://iqss.slack.com/archives/C06FWJ0FV2R/p1707935795390489

**Comment by MellyGray** [comment]
@ekraffmiller I updated the code to set :latest-published as the default version to match JSF behavior as you suggested

**Comment by ekraffmiller** [comment]
@MellyGray since we are creating an action item for fixing the default version shown as discussed here https://iqss.slack.com/archives/C06FWJ0FV2R/p1708016216373459,  I think it's ok to keep everything as :latest, what do you think? Since our ultimate solution will be changing this logic anyway.

**Comment by pdurbin** [comment]
I'm removing the waiting label because this pull request was just merged:

- https://github.com/IQSS/dataverse/pull/10246

**Review by ekraffmiller — APPROVED** [review]
Looks good, approved!

**Review by GPortas — APPROVED** [review]
LGTM

**Pull request merged**
